### ISSUE TITLE
Gaffelfråga

### ISSUE THREAD

**Issue by makedatanotlore** [progund/cave-sprint-1#5]
@rikardfroberg 
Tja, är det lugnt att gaffla ert arkiv för uppgiften eller stör det? Finns det ett alternativ ni skulle föredra? Märkt att jag blivit överlistad av några pull-requests och skickat dem hit och nu kan jag knappt sova på nätterna

**Comment by rikardfroberg** [comment]
Hej!

Gör en fork om du tycker det är enklast!

Oss kvittar det. Ni kan ju clone:a repot så inget hindrar er från att lägga upp det på er egen sida - kanske enklast att göra en fork i så fall :)

/R
